[project]
name = "data-napkin-math"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.11.22",
    "pandas>=2.2.3",
    "python-fasthtml>=0.12.4",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]
